spring.application.name=COURS-SERVICE
server.port=8090

# =================================
# DATABASE
# =================================

spring.datasource.url=jdbc:postgresql://localhost:5432/cours
spring.datasource.username=anwar
spring.datasource.password=anwar123
spring.datasource.driver-class-name=org.postgresql.Driver

# =================================
# JPA / HIBERNATE
# =================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =================================
# JACKSON
# =================================

spring.jackson.deserialization.fail-on-null-for-primitives=false

# =================================
# MAIL
# =================================

spring.mail.host=ssl0.ovh.net
spring.mail.port=587
spring.mail.username=mino.support@minolingo.online
spring.mail.password=mr?FAtB2AUP&i2b
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.url=https://minolingo.online

# =================================
# FILE UPLOAD
# =================================

file.upload-dir=/var/www/uploads
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# =================================
# EUREKA CLIENT
# =================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# =================================
# AI MODEL
# =================================

avatar.ai.model=qwen2.5:3b
